name: echo_flutter_news
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.8.1
  google_fonts: ^6.1.0
  basic_utils: ^5.7.0
  firebase_auth: ^5.3.4
  firebase_database: ^11.2.0
  cloud_firestore: ^5.5.1
  favorite_button: ^0.0.4
  # easy_search_bar: ^2.5.0
  url_launcher: ^6.2.2
  choice: ^2.3.0
  transparent_image: ^2.0.1
  intl: ^0.18.1
  flutter_spinkit: ^5.2.0
  flutter_dotenv: ^5.1.0
  web: ^1.1.0 
  flutter_easy_search_bar: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/placeholder.png
    - .env