// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDECq61wcb1bCN1Xnpr0gbUt0Xq_30k_EE',
    appId: '1:277373485083:web:9a3a2890e790e50d9b78be',
    messagingSenderId: '277373485083',
    projectId: 'echoflutternews',
    authDomain: 'echoflutternews.firebaseapp.com',
    storageBucket: 'echoflutternews.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5r7RfPQ2UMRx73ldOEyZEkKSxySu0hh8',
    appId: '1:277373485083:android:bc6b06503fc340679b78be',
    messagingSenderId: '277373485083',
    projectId: 'echoflutternews',
    storageBucket: 'echoflutternews.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyDECq61wcb1bCN1Xnpr0gbUt0Xq_30k_EE",
    authDomain: "echoflutternews.firebaseapp.com",
    projectId: "echoflutternews",
    storageBucket: "echoflutternews.firebasestorage.app",
    messagingSenderId: "277373485083",
    appId: "1:277373485083:web:9a3a2890e790e50d9b78be",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1hCLtKTZiKUopqzSg0V2p6L0j3spkro8',
    appId: '1:277373485083:ios:9f8334fea0a8cd449b78be',
    messagingSenderId: '277373485083',
    projectId: 'echoflutternews',
    storageBucket: 'echoflutternews.firebasestorage.app',
    iosBundleId: 'com.example.newsAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDECq61wcb1bCN1Xnpr0gbUt0Xq_30k_EE',
    appId: '1:277373485083:web:caa55a013dfb08e49b78be',
    messagingSenderId: '277373485083',
    projectId: 'echoflutternews',
    authDomain: 'echoflutternews.firebaseapp.com',
    storageBucket: 'echoflutternews.firebasestorage.app',
  );
}
